//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OREX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public string Company { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Phone4 { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string WebPage { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreditLimit { get; set; }
        public Nullable<int> SalesPerson { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public Nullable<bool> SalesInvoice { get; set; }
        public Nullable<int> Category { get; set; }
        public string TIN { get; set; }
    }
}
